### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by JoeMurray** [ppschweiz/docker-civicrm#2]
Hi @ppschweiz,
I'm not sure if you are still active or still interested in CiviCRM docker integration. As a community we have a couple of good student proposals for Google Summer of Code 2018 to work on docker. Would be great to have some assistance in mentoring them if you are still interested in this area.

Cheers,
Joe

**Comment by cambid** [comment]
Hi Joe

We are still using docker for our infrastructure (f.e. CiviCRM or OTRS) but unfortunately we don't have the time to mentor students in GSOC 2018.

Regards
Jan

**Comment by JoeMurray** [comment]
Thanks, Jan.
